[package]
name = "benchmarks"
version = "0.1.0"
edition = "2018"

[dependencies]
harfbuzz_rs = { git = "https://github.com/harfbuzz/harfbuzz_rs/", rev = "43f0fb5" }
harfrust = { path = "../" }
read-fonts = "0.29.0"

[features]
default = ["hb"]
hb = []
